MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

# Custom EVENTS
MOVED_IN_BOMB_RANGE = "MOVED_IN_BOMB_RANGE"
MOVED_OUT_BOMB_RANGE = "MOVED_OUT_BOMB_RANGE"
STAYED_IN_BOMB_RANGE = "STAYED_IN_BOMB_RANGE"
STAYED_OUT_BOMB_RANGE = "STAYED_OUT_BOMB_RANGE"

MOVED_CLOSER_TO_ENEMY = "MOVED_CLOSER_TO_ENEMY"
MOVED_AWAY_FROM_ENEMY = "MOVED_AWAY_FROM_ENEMY"


MOVED_INTO_EXPLOSION = "MOVED_INTO_EXPLOSION"
